### Data Cleaning

In this notebook we will clean and combine the raw data in CSVs collected from the publicly available [Hourly Load Data Archives](http://www.ercot.com/gridinfo/load/load_hist/index.html). These data sets contain the hourly energy load, measured in MW, for the eight regions that make up the electric grid monitored by the Electric Reliability Council of Texas and spans from 2008-2019. The goal of cleaning and compiling the data into one CSV is to build statistical models in order to forecast future energy demand.

To begin, we'll load in our basics python libraries:

In [247]:
#Holy Trinity
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

And now proceed with loading in the raw data from the parent website and see what we have to work with. Take note that the naming convention of the CSVs from ERCOT changed after 2014:

In [248]:
ercot2008_df = pd.read_csv("capstone_data/2008_ERCOT_Hourly_Load_Data.csv")
ercot2009_df = pd.read_csv("capstone_data/2009_ERCOT_Hourly_Load_Data.csv")
ercot2010_df = pd.read_csv("capstone_data/2010_ERCOT_Hourly_Load_Data.csv")
ercot2011_df = pd.read_csv("capstone_data/2011_ERCOT_Hourly_Load_Data.csv")
ercot2012_df = pd.read_csv("capstone_data/2012_ERCOT_Hourly_Load_Data.csv")
ercot2013_df = pd.read_csv("capstone_data/2013_ERCOT_Hourly_Load_Data.csv")
ercot2014_df = pd.read_csv("capstone_data/2014_ERCOT_Hourly_Load_Data.csv")
ercot2015_df = pd.read_csv('capstone_data/native_Load_2015.csv')
ercot2016_df = pd.read_csv('capstone_data/native_Load_2016.csv')
ercot2017_df = pd.read_csv('capstone_data/native_Load_2017.csv')
ercot2018_df = pd.read_csv('capstone_data/native_Load_2018.csv')
ercot2019_df = pd.read_csv('capstone_data/native_Load_2019.csv')

Let's look at some of the data in our new dataframes: 

In [249]:
ercot2008_df.head()

Hour_End        COAST         EAST     FAR_WEST        NORTH  \
0  1/1/2008 1:00  7582.426275  1137.197278  1289.741591  1120.591245   
1  1/1/2008 2:00  7483.387277  1129.312429  1320.549720  1130.163920   
2  1/1/2008 3:00  7381.744778  1155.484647  1328.442079  1129.355056   
3  1/1/2008 4:00  7452.871868  1209.918355  1344.322369  1148.919804   
4  1/1/2008 5:00  7530.354017  1265.055389  1355.020035  1171.267839   

       NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
0  10782.48780  1894.920943  4857.044340  932.251506  29596.66098  
1  10873.00119  1826.089194  4867.512567  939.958255  29569.97455  
2  10952.63748  1832.883827  4849.639885  951.322118  29581.50987  
3  11104.17876  1819.248340  4858.047321  967.450488  29904.95730  
4  11369.93504  1834.777369  4962.345559  996.055206  30484.81045

In [250]:
ercot2009_df.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0  1/1/2009 1:00  7300.317873  1173.516507  1221.195150  809.370368   
1  1/1/2009 2:00  7174.769899  1161.605492  1221.723993  801.758344   
2  1/1/2009 3:00  7108.488956  1162.793073  1221.679497  796.833243   
3  1/1/2009 4:00  7024.863242  1177.509559  1226.780490  802.548898   
4  1/1/2009 5:00  7049.567942  1194.823014  1236.579870  814.159655   

       NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
0  10329.68751  1841.693608  4601.280319  902.794867  28179.85620  
1  10284.11578  1769.591445  4533.730682  903.455645  27850.75128  
2  10238.59455  1722.553266  4452.980186  901.649905  27605.57268  
3  10315.93065  1678.045689  4405.209584  909.355940  27540.24405  
4  10521.47215  1686.109335  4451.359225  925.522322  27879.59352

In [251]:
ercot2010_df.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0  1/1/2010 1:00  7775.456846  1238.179861  1237.649967  877.672404   
1  1/1/2010 2:00  7704.815982  1236.050964  1248.907364  883.621724   
2  1/1/2010 3:00  7650.575724  1244.073140  1251.207485  881.155327   
3  1/1/2010 4:00  7666.708317  1253.211110  1260.419002  894.330100   
4  1/1/2010 5:00  7744.960869  1284.055257  1264.653516  906.325283   

       NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
0  12405.84941  2467.581039  5031.931981  1059.742927  32094.06444  
1  12485.81486  2436.025369  5111.468920  1064.617365  32171.32255  
2  12559.46112  2414.440222  5168.887617  1071.951825  32241.75246  
3  12671.84795  2383.948564  5241.889124  1086.839061  32459.19323  
4  12912.26730  2498.179406  5401.453950  1111.855463  33123.75105

In [252]:
ercot2011_df.head()

Hour_End        COAST        EAST     FAR_WEST       NORTH  \
0  1/1/2011 1:00  7242.844978  919.318501  1273.185354  762.181838   
1  1/1/2011 2:00  7028.298944  906.680146  1273.258677  762.644083   
2  1/1/2011 3:00  6870.407297  877.968337  1272.137325  763.843552   
3  1/1/2011 4:00  6795.107575  863.683835  1275.681005  775.352756   
4  1/1/2011 5:00  6758.472347  888.934818  1279.740460  788.251673   

        NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
0  10038.701860  2033.434272  4448.833193  943.943487  27662.44348  
1   9982.845460  1964.750313  4401.280885  930.286207  27250.04472  
2   9870.152864  1885.766434  4320.909860  922.040412  26783.22608  
3   9962.356063  1822.641403  4255.834185  925.811668  26676.46849  
4  10157.366640  1816.829635  4241.214054  937.992915  26868.80254

In [253]:
ercot2012_df.head()

Hour_End        COAST        EAST     FAR_WEST       NORTH  \
0  1/1/2012 1:00  7748.160500  878.438488  1289.746813  652.153054   
1  1/1/2012 2:00  7559.728089  839.092904  1294.272245  643.483530   
2  1/1/2012 3:00  7337.789042  817.995707  1296.491345  631.940923   
3  1/1/2012 4:00  7161.895539  814.967883  1297.417294  631.428520   
4  1/1/2012 5:00  6984.460743  843.952578  1309.534911  640.892563   

       NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
0  8648.989316  2105.379142  4162.162310  849.000892  26334.03052  
1  8553.212708  2047.755534  4070.416593  845.097364  25853.05897  
2  8461.317967  1961.909818  3946.994332  840.902849  25295.34198  
3  8438.693857  1893.148232  3884.929253  845.452257  24967.93284  
4  8565.433348  1867.358425  3911.610238  862.369386  24985.61219

In [254]:
ercot2013_df.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0  1/1/2013 1:00  7607.189871  1074.024285  1411.823159  763.069242   
1  1/1/2013 2:00  7389.267519  1035.189180  1403.601093  754.425986   
2  1/1/2013 3:00  7179.748411  1036.216739  1395.131213  746.215515   
3  1/1/2013 4:00  7039.692524  1032.777439  1395.593012  749.028766   
4  1/1/2013 5:00  6991.412764  1042.906443  1401.239529  757.148203   

        NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
0  10370.322920  2206.945802  4368.528687  883.029500  28684.93347  
1  10153.942810  2160.082197  4233.635250  872.532258  28002.67629  
2   9989.243532  2065.369913  4082.897707  868.951334  27363.77436  
3   9947.855512  1991.151652  4010.524187  865.799032  27032.42212  
4  10097.444230  1954.963942  4038.678495  879.988054  27163.78166

In [255]:
ercot2014_df.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0  1/1/2014 1:00  9101.691219  1338.197939  1820.206244  793.458458   
1  1/1/2014 2:00  8907.975782  1328.940064  1809.180861  791.141630   
2  1/1/2014 3:00  8738.460973  1317.990846  1804.524573  789.791906   
3  1/1/2014 4:00  8622.671259  1325.545134  1807.227126  797.195877   
4  1/1/2014 5:00  8615.480468  1348.596187  1816.456043  810.868332   

       NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
0  12298.80115  3236.109065  6121.146143  1102.523505  35812.13372  
1  12297.10982  3246.493375  6091.018850  1098.774771  35570.63516  
2  12285.29525  3217.721388  6060.017515  1097.716762  35311.51921  
3  12368.07007  3165.203545  6017.610069  1105.891248  35209.41433  
4  12639.01736  3134.199330  6072.948097  1123.927314  35561.49313

In [256]:
ercot2015_df.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0  1/1/2015 1:00  9844.200268  1350.784678  2078.060021  901.770195   
1  1/1/2015 2:00  9653.456269  1333.434943  2057.993265  890.150373   
2  1/1/2015 3:00  9502.299659  1323.908498  2039.019542  880.926639   
3  1/1/2015 4:00  9474.478036  1325.951405  2027.431312  883.990576   
4  1/1/2015 5:00  9554.370489  1339.675290  2026.809889  894.320303   

       NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
0  13640.02498  3607.904503  6731.301663  1470.814721  39624.86103  
1  13425.12194  3609.619438  6602.935629  1440.832944  39013.54480  
2  13286.07091  3573.158363  6530.663273  1430.495044  38566.54193  
3  13310.89259  3538.420320  6503.367925  1423.806348  38488.33851  
4  13423.34550  3542.905394  6603.227872  1428.180823  38812.83556

In [257]:
ercot2016_df.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0  1/1/2016 1:00  9001.477932  1148.358788  2107.895986  788.543919   
1  1/1/2016 2:00  8864.555456  1134.909662  2100.702470  782.355108   
2  1/1/2016 3:00  8745.758728  1126.864026  2099.966167  781.237004   
3  1/1/2016 4:00  8689.879755  1129.417663  2104.947864  785.264364   
4  1/1/2016 5:00  8733.703094  1141.769602  2117.072608  790.248115   

       NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
0  11409.33904  2829.993195  5479.057816  1088.091916  33852.75859  
1  11235.17494  2830.075196  5405.955778  1080.369336  33434.09794  
2  11151.96522  2789.470654  5334.159606  1069.644619  33099.06602  
3  11209.70107  2757.999808  5302.938201  1073.658885  33053.80761  
4  11428.71696  2769.678996  5364.298843  1096.410845  33441.89907

In [258]:
ercot2017_df.head()

Hour Ending    COAST    EAST    FWEST   NORTH    NCENT    SOUTH    SCENT  \
0  1/1/2017 1:00  8791.79  896.75  1997.72  683.62  9239.15  2366.63  4490.78   
1  1/1/2017 2:00  8569.71  865.93  1997.78  677.97  9105.00  2332.74  4370.66   
2  1/1/2017 3:00  8326.43  839.05  1993.70  672.00  8988.04  2237.51  4210.65   
3  1/1/2017 4:00  8137.50  822.83  1995.54  675.27  8979.15  2178.10  4088.71   
4  1/1/2017 5:00  8011.87  814.02  1995.25  663.62  9033.55  2133.95  4021.76   

     WEST     ERCOT  
0  954.19  29420.64  
1  951.03  28870.81  
2  944.36  28211.72  
3  943.19  27820.29  
4  954.94  27628.96

In [259]:
ercot2018_df.head()

HourEnding     COAST     EAST    FWEST    NORTH     NCENT    SOUTH  \
0  1/1/2018 1:00  11425.98  1852.66  2823.41  1135.36  18584.34  3831.65   
1  1/1/2018 2:00  11408.42  1850.17  2809.75  1136.63  18524.14  3988.27   
2  1/1/2018 3:00  11405.20  1858.27  2797.80  1135.93  18532.06  4076.09   
3  1/1/2018 4:00  11450.56  1879.62  2807.79  1146.07  18647.44  4154.94   
4  1/1/2018 5:00  11631.34  1876.48  2822.99  1154.19  19002.10  4247.45   

     SCENT     WEST     ERCOT  
0  9151.19  1762.47  50567.07  
1  9144.99  1754.72  50617.09  
2  9141.04  1747.92  50694.30  
3  9157.96  1755.20  50999.59  
4  9214.33  1774.85  51723.73

In [260]:
ercot2019_df.head()

HourEnding    COAST     EAST    FWEST   NORTH     NCENT    SOUTH  \
0  1/1/2019 1:00  9783.59  1264.19  3164.72  827.76  11697.77  3066.89   
1  1/1/2019 2:00  9726.06  1270.49  3178.95  830.26  11787.94  3140.38   
2  1/1/2019 3:00  9654.37  1269.50  3200.88  831.51  11861.63  3137.72   
3  1/1/2019 4:00  9631.74  1243.17  3221.96  839.69  11989.11  3105.50   
4  1/1/2019 5:00  9698.89  1309.57  3240.63  848.67  12219.11  3078.26   

     SCENT     WEST     ERCOT  
0  5993.97  1282.54  37081.44  
1  6029.77  1295.13  37258.99  
2  6043.35  1301.23  37300.19  
3  6086.41  1305.98  37423.54  
4  6180.94  1319.14  37895.21

After comparing the column names of each of the datasets, we can see that the naming convention has also changed, but the data remains appropriately recorded. Let's adjust the names of the last three datasets to match those of the previous datasets:

In [261]:
#Rename columns
ercot2017_df = ercot2017_df.rename(columns = {'Hour Ending':'Hour_End', 'FWEST':'FAR_WEST',
                                    'NCENT':'NORTH_C', 'SOUTH':'SOUTHERN', 'SCENT':'SOUTH_C'})

ercot2018_df = ercot2018_df.rename(columns = {'HourEnding':'Hour_End', 'FWEST':'FAR_WEST',
                                    'NCENT':'NORTH_C', 'SOUTH':'SOUTHERN', 'SCENT':'SOUTH_C'})

ercot2019_df = ercot2019_df.rename(columns = {'HourEnding':'Hour_End', 'FWEST':'FAR_WEST',
                                    'NCENT':'NORTH_C', 'SOUTH':'SOUTHERN', 'SCENT':'SOUTH_C'})

Check to see that the change went through: 

In [262]:
ercot2017_df.head()

Hour_End    COAST    EAST  FAR_WEST   NORTH  NORTH_C  SOUTHERN  \
0  1/1/2017 1:00  8791.79  896.75   1997.72  683.62  9239.15   2366.63   
1  1/1/2017 2:00  8569.71  865.93   1997.78  677.97  9105.00   2332.74   
2  1/1/2017 3:00  8326.43  839.05   1993.70  672.00  8988.04   2237.51   
3  1/1/2017 4:00  8137.50  822.83   1995.54  675.27  8979.15   2178.10   
4  1/1/2017 5:00  8011.87  814.02   1995.25  663.62  9033.55   2133.95   

   SOUTH_C    WEST     ERCOT  
0  4490.78  954.19  29420.64  
1  4370.66  951.03  28870.81  
2  4210.65  944.36  28211.72  
3  4088.71  943.19  27820.29  
4  4021.76  954.94  27628.96

In [263]:
ercot2018_df.head()

Hour_End     COAST     EAST  FAR_WEST    NORTH   NORTH_C  SOUTHERN  \
0  1/1/2018 1:00  11425.98  1852.66   2823.41  1135.36  18584.34   3831.65   
1  1/1/2018 2:00  11408.42  1850.17   2809.75  1136.63  18524.14   3988.27   
2  1/1/2018 3:00  11405.20  1858.27   2797.80  1135.93  18532.06   4076.09   
3  1/1/2018 4:00  11450.56  1879.62   2807.79  1146.07  18647.44   4154.94   
4  1/1/2018 5:00  11631.34  1876.48   2822.99  1154.19  19002.10   4247.45   

   SOUTH_C     WEST     ERCOT  
0  9151.19  1762.47  50567.07  
1  9144.99  1754.72  50617.09  
2  9141.04  1747.92  50694.30  
3  9157.96  1755.20  50999.59  
4  9214.33  1774.85  51723.73

In [264]:
ercot2019_df.head()

Hour_End    COAST     EAST  FAR_WEST   NORTH   NORTH_C  SOUTHERN  \
0  1/1/2019 1:00  9783.59  1264.19   3164.72  827.76  11697.77   3066.89   
1  1/1/2019 2:00  9726.06  1270.49   3178.95  830.26  11787.94   3140.38   
2  1/1/2019 3:00  9654.37  1269.50   3200.88  831.51  11861.63   3137.72   
3  1/1/2019 4:00  9631.74  1243.17   3221.96  839.69  11989.11   3105.50   
4  1/1/2019 5:00  9698.89  1309.57   3240.63  848.67  12219.11   3078.26   

   SOUTH_C     WEST     ERCOT  
0  5993.97  1282.54  37081.44  
1  6029.77  1295.13  37258.99  
2  6043.35  1301.23  37300.19  
3  6086.41  1305.98  37423.54  
4  6180.94  1319.14  37895.21

The column names were successfully changed. 

---

### Cleaning the Missing Dates in 2018 Data

After looking further into one of the datasets we see that the date is misrecorded with a 5 digit number rather than a proper date. This is occuring every 24 hours at midnight, the 0:00 hour. 

In [265]:
#Observe the missing date patterns on the 0:00 hour
ercot2018_df.loc[22:48]

Hour_End     COAST     EAST  FAR_WEST    NORTH   NORTH_C  SOUTHERN  \
22  1/1/2018 23:00  13104.63  1945.96   2831.64  1122.27  18993.50   5250.64   
23           43102  12677.63  1893.64   2773.98  1101.11  18346.96   5072.79   
24   1/2/2018 1:00  12954.54  1877.85   2908.41  1109.40  18245.55   5105.51   
25   1/2/2018 2:00  12762.33  1863.55   2896.25  1112.72  18041.58   5011.84   
26   1/2/2018 3:00  12672.32  1870.35   2903.21  1121.27  17954.64   4964.11   
27   1/2/2018 4:00  12720.79  1884.48   2914.42  1129.76  17999.01   4951.62   
28   1/2/2018 5:00  12982.67  1923.42   2931.03  1146.11  18313.72   4972.13   
29   1/2/2018 6:00  13540.02  2006.80   2974.96  1186.32  19110.14   5129.00   
30   1/2/2018 7:00  14259.42  2114.64   3034.23  1242.55  20146.48   5378.29   
31   1/2/2018 8:00  14662.85  2187.38   3072.45  1280.04  20703.41   5512.89   
32   1/2/2018 9:00  14847.38  2235.56   3040.62  1297.94  20821.65   5606.69   
33  1/2/2018 10:00  15078.54  2254.58   3034.99  1303.39  20987.82   5695.72   
34  1/2/2018 11:00  15249.14  2190.93   3030.59  1295.13  20975.02   5739.27   
35  1/2/2018 12:00  15162.50  2152.01   2996.40  1274.25  20799.50   5711.04   
36  1/2/2018 13:00  14982.16  2157.80   2946.62  1241.67  20494.03   5621.87   
37  1/2/2018 14:00  14868.70  2125.45   2921.38  1203.33  20298.20   5543.70   
38  1/2/2018 15:00  14784.34  2085.83   2897.57  1186.08  20172.90   5527.97   
39  1/2/2018 16:00  14708.81  2107.65   2835.93  1179.92  20255.11   5538.81   
40  1/2/2018 17:00  14844.78  2126.90   2809.17  1174.96  20683.04   5616.72   
41  1/2/2018 18:00  15397.70  2222.17   2859.86  1220.23  21580.65   5785.47   
42  1/2/2018 19:00  15655.35  2274.21   3003.97  1264.50  22168.94   6034.88   
43  1/2/2018 20:00  15562.07  2258.65   3044.37  1264.40  22015.78   6093.73   
44  1/2/2018 21:00  15390.07  2229.26   3054.22  1255.74  21687.86   6082.71   
45  1/2/2018 22:00  15016.04  2186.81   3025.22  1226.15  21024.75   5989.84   
46  1/2/2018 23:00  14447.10  2087.45   2976.39  1185.46  19962.69   5792.93   
47           43103  13951.71  2015.03   2931.94  1153.91  19261.95   5582.65   
48   1/3/2018 1:00  13364.63  1946.17   2802.05  1128.88  18582.42   5174.95   

    SOUTH_C     WEST     ERCOT  
22  9373.66  1779.75  54402.04  
23  8960.33  1724.36  52550.80  
24  7348.84  1630.07  51180.17  
25  7172.20  1632.21  50492.67  
26  7093.98  1640.71  50220.58  
27  7115.69  1660.43  50376.20  
28  7280.40  1696.70  51246.18  
29  7655.65  1756.40  53359.29  
30  8150.99  1849.02  56175.63  
31  8469.28  1916.99  57805.27  
32  8577.66  1920.04  58347.54  
33  8691.77  1930.07  58976.88  
34  8765.60  1924.07  59169.75  
35  8733.73  1898.65  58728.07  
36  8632.56  1866.74  57943.44  
37  8537.78  1843.34  57341.89  
38  8497.12  1826.63  56978.44  
39  8585.93  1818.63  57030.79  
40  8819.10  1810.78  57885.46  
41  9271.57  1846.10  60183.75  
42  9616.56  1930.27  61948.68  
43  9593.22  1949.40  61781.61  
44  9477.47  1948.08  61125.41  
45  9172.01  1908.32  59549.12  
46  8685.52  1847.18  56984.71  
47  8288.25  1805.31  54990.74  
48  9223.09  1709.98  53932.18

Let's fix the 2018 data's date recorded in `Hour_End` issue. We can separate the `Hour_end` column so that we can operate on it. The process will be to separate the date from the hour, manually fill in the hour values with "0:00" since they all occur at the same hour, and then changed the date by replacing the 5 digit numbers with the date from the row ahead. 

First, let's look at what type of data `Hour_End` is:

In [266]:
#Look at datatypes
ercot2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Hour_End  8760 non-null   object 
 1   COAST     8760 non-null   float64
 2   EAST      8760 non-null   float64
 3   FAR_WEST  8760 non-null   float64
 4   NORTH     8760 non-null   float64
 5   NORTH_C   8760 non-null   float64
 6   SOUTHERN  8760 non-null   float64
 7   SOUTH_C   8760 non-null   float64
 8   WEST      8760 non-null   float64
 9   ERCOT     8760 non-null   float64
dtypes: float64(9), object(1)
memory usage: 684.5+ KB


Since the data recorded in `Hour_End` is still an object type, we'll split the string so that the date is separated from the hour. 

In [267]:
#Separate the date and hours
ercot2018df_split = pd.DataFrame(ercot2018_df['Hour_End'].str.split(' ').tolist(), \
                                 columns = ['date', 'hour', 'DST'])
#Check if separated correctly
ercot2018df_split.head()

date  hour   DST
0  1/1/2018  1:00  None
1  1/1/2018  2:00  None
2  1/1/2018  3:00  None
3  1/1/2018  4:00  None
4  1/1/2018  5:00  None

It turns out there is a least one value recorded as `DST`, or Daylight Savings Time. We'll address that later. Now that the hours are isolated, we can check the current number of missing values in `hour` column:

In [268]:
#Check current number of missing values in 'hour' column
ercot2018df_split.loc[ercot2018df_split['hour'].isna()]

date  hour   DST
23    43102  None  None
47    43103  None  None
71    43104  None  None
95    43105  None  None
119   43106  None  None
...     ...   ...   ...
8663  43462  None  None
8687  43463  None  None
8711  43464  None  None
8735  43465  None  None
8759  43466  None  None

[365 rows x 3 columns]

We have a year's worth (365 rows) of missing hours. This help confirms that the hours are missing in this 24 hour pattern. Now let's fill in those values with the correct hour, '0:00'.

In [269]:
#Fill in missing hours with 0:00
ercot2018df_split['hour'] = ercot2018df_split['hour'].fillna('0:00')

In [270]:
#Check that row 2 of 'hour' is 0:00
ercot2018df_split.head(30)

date   hour   DST
0   1/1/2018   1:00  None
1   1/1/2018   2:00  None
2   1/1/2018   3:00  None
3   1/1/2018   4:00  None
4   1/1/2018   5:00  None
5   1/1/2018   6:00  None
6   1/1/2018   7:00  None
7   1/1/2018   8:00  None
8   1/1/2018   9:00  None
9   1/1/2018  10:00  None
10  1/1/2018  11:00  None
11  1/1/2018  12:00  None
12  1/1/2018  13:00  None
13  1/1/2018  14:00  None
14  1/1/2018  15:00  None
15  1/1/2018  16:00  None
16  1/1/2018  17:00  None
17  1/1/2018  18:00  None
18  1/1/2018  19:00  None
19  1/1/2018  20:00  None
20  1/1/2018  21:00  None
21  1/1/2018  22:00  None
22  1/1/2018  23:00  None
23     43102   0:00  None
24  1/2/2018   1:00  None
25  1/2/2018   2:00  None
26  1/2/2018   3:00  None
27  1/2/2018   4:00  None
28  1/2/2018   5:00  None
29  1/2/2018   6:00  None

Success, 23rd row has been changed to 0:00.

In [271]:
#Check again current number of missing values in 'hour' column
ercot2018df_split.loc[ercot2018df_split['hour'].isna()]

Empty DataFrame
Columns: [date, hour, DST]
Index: []

And now we've confirmed that there are no more missing values for the `hour` column.

---

#### Fix the 'date' column. Correct the date in the 5 digit places
Now let's fix the date column to have the correct date. We'll do this by using a regex to find the rows with the 5 digits, replace those with NaN, and then replace them with the date from the following row. 

In [272]:
#Replace the five digit 'date' rows with nan
ercot2018df_split = ercot2018df_split.replace(to_replace = '\d{5}', value = np.nan, regex = True)

In [273]:
#Check to see if five digit 'date' have been replaced with NaN
ercot2018df_split.loc[23:48]

date   hour   DST
23       NaN   0:00  None
24  1/2/2018   1:00  None
25  1/2/2018   2:00  None
26  1/2/2018   3:00  None
27  1/2/2018   4:00  None
28  1/2/2018   5:00  None
29  1/2/2018   6:00  None
30  1/2/2018   7:00  None
31  1/2/2018   8:00  None
32  1/2/2018   9:00  None
33  1/2/2018  10:00  None
34  1/2/2018  11:00  None
35  1/2/2018  12:00  None
36  1/2/2018  13:00  None
37  1/2/2018  14:00  None
38  1/2/2018  15:00  None
39  1/2/2018  16:00  None
40  1/2/2018  17:00  None
41  1/2/2018  18:00  None
42  1/2/2018  19:00  None
43  1/2/2018  20:00  None
44  1/2/2018  21:00  None
45  1/2/2018  22:00  None
46  1/2/2018  23:00  None
47       NaN   0:00  None
48  1/3/2018   1:00  None

Now the rows have been correctly changed to nulls. Now let's replace them with the correct date, using the one in the row ahead.

In [274]:
#Now forward fill the 'hour'  column where NaN
ercot2018df_split['date'] = ercot2018df_split['date'].fillna(method = 'bfill')

In [275]:
#Check to see that the 23rd and 47th row have the correct date
ercot2018df_split.loc[23:48]

date   hour   DST
23  1/2/2018   0:00  None
24  1/2/2018   1:00  None
25  1/2/2018   2:00  None
26  1/2/2018   3:00  None
27  1/2/2018   4:00  None
28  1/2/2018   5:00  None
29  1/2/2018   6:00  None
30  1/2/2018   7:00  None
31  1/2/2018   8:00  None
32  1/2/2018   9:00  None
33  1/2/2018  10:00  None
34  1/2/2018  11:00  None
35  1/2/2018  12:00  None
36  1/2/2018  13:00  None
37  1/2/2018  14:00  None
38  1/2/2018  15:00  None
39  1/2/2018  16:00  None
40  1/2/2018  17:00  None
41  1/2/2018  18:00  None
42  1/2/2018  19:00  None
43  1/2/2018  20:00  None
44  1/2/2018  21:00  None
45  1/2/2018  22:00  None
46  1/2/2018  23:00  None
47  1/3/2018   0:00  None
48  1/3/2018   1:00  None

In [276]:
#Find where the hour is 0:00 and check the dates
ercot2018df_split.loc[ercot2018df_split['hour'] == '0:00']

date  hour   DST
23      1/2/2018  0:00  None
47      1/3/2018  0:00  None
71      1/4/2018  0:00  None
95      1/5/2018  0:00  None
119     1/6/2018  0:00  None
...          ...   ...   ...
8663  12/28/2018  0:00  None
8687  12/29/2018  0:00  None
8711  12/30/2018  0:00  None
8735  12/31/2018  0:00  None
8759         NaN  0:00  None

[365 rows x 3 columns]

SUCCESS! They all have dates except the last row. 

The data includes one hour from the next year. Since since we cannot back fill it with a row after that date, we need to fill in the last row's date manually. 

*I've also checked the other datasets to see that this is true for each one and each dataset is missing the first hour of the year. I've decided to keep this last row of each dataset so that when all the data is concatenated this last row hour is preserved.* 

In [277]:
#Fill in last hour of the dataset to be the next year
ercot2018df_split['date'].loc[8759] = '01/01/2019'

In [278]:
#Check to see if last date is fixed
ercot2018df_split.loc[ercot2018df_split['hour'] == '0:00'].tail()

date  hour   DST
8663  12/28/2018  0:00  None
8687  12/29/2018  0:00  None
8711  12/30/2018  0:00  None
8735  12/31/2018  0:00  None
8759  01/01/2019  0:00  None

We've successfully corrected the dates, now we can proceed to combining back `date` and `hour`.

In [279]:
#Combine date and hour columns
ercot2018df_split['date'] = ercot2018df_split['date'] + ' ' + ercot2018df_split['hour'] 

In [280]:
ercot2018df_split.head()

date  hour   DST
0  1/1/2018 1:00  1:00  None
1  1/1/2018 2:00  2:00  None
2  1/1/2018 3:00  3:00  None
3  1/1/2018 4:00  4:00  None
4  1/1/2018 5:00  5:00  None

Success. 
Now first find the daylight savings time row, `DST`. And *then* drop the unnecessary `hour` and `DST` columns.

In [281]:
#Find DST row
ercot2018df_split.loc[ercot2018df_split['DST'] == 'DST']

date   hour  DST
7369  11/04/2018 02:00  02:00  DST

For this project, we will drop the DST hour. Note that in future modeling this row could be handled differently for better accuracy on the models. Row 7369 is the row we will drop AFTER combining the corrected dates back to the dataset. 

In [282]:
#Drop DST row
ercot2018df_split = ercot2018df_split.drop(columns = ['hour', 'DST'])

In [283]:
#Check
ercot2018df_split.head()

date
0  1/1/2018 1:00
1  1/1/2018 2:00
2  1/1/2018 3:00
3  1/1/2018 4:00
4  1/1/2018 5:00

Everthing looks good, columns `hour` and `DST` have been dropped. We're now ready to assign the clean dates back to the main 2018 datframe.

---

Let's check that the number of rows in the clean dates are equal to the number of rows in the original dataset:

In [284]:
#Eyes on target
ercot2018_df.head(5)

Hour_End     COAST     EAST  FAR_WEST    NORTH   NORTH_C  SOUTHERN  \
0  1/1/2018 1:00  11425.98  1852.66   2823.41  1135.36  18584.34   3831.65   
1  1/1/2018 2:00  11408.42  1850.17   2809.75  1136.63  18524.14   3988.27   
2  1/1/2018 3:00  11405.20  1858.27   2797.80  1135.93  18532.06   4076.09   
3  1/1/2018 4:00  11450.56  1879.62   2807.79  1146.07  18647.44   4154.94   
4  1/1/2018 5:00  11631.34  1876.48   2822.99  1154.19  19002.10   4247.45   

   SOUTH_C     WEST     ERCOT  
0  9151.19  1762.47  50567.07  
1  9144.99  1754.72  50617.09  
2  9141.04  1747.92  50694.30  
3  9157.96  1755.20  50999.59  
4  9214.33  1774.85  51723.73

In [285]:
#Are the number of rows equal? 
ercot2018df_split.count() == ercot2018_df['Hour_End'].count()

date    True
dtype: bool

Since they are equal in length we can proceed and assign ercot2018_df `Hour_End` the new clean ercot2018df_split `date`.

In [286]:
#Replace old with new
ercot2018_df['Hour_End'] = ercot2018df_split['date']

Let's see if it worked!

In [287]:
#Specifically check that row 23 and 47 'HourEnd' are correct 
ercot2018_df.head(50)

Hour_End     COAST     EAST  FAR_WEST    NORTH   NORTH_C  SOUTHERN  \
0    1/1/2018 1:00  11425.98  1852.66   2823.41  1135.36  18584.34   3831.65   
1    1/1/2018 2:00  11408.42  1850.17   2809.75  1136.63  18524.14   3988.27   
2    1/1/2018 3:00  11405.20  1858.27   2797.80  1135.93  18532.06   4076.09   
3    1/1/2018 4:00  11450.56  1879.62   2807.79  1146.07  18647.44   4154.94   
4    1/1/2018 5:00  11631.34  1876.48   2822.99  1154.19  19002.10   4247.45   
5    1/1/2018 6:00  11939.41  1903.01   2841.67  1182.43  19477.36   4389.05   
6    1/1/2018 7:00  12268.83  1961.79   2854.74  1212.75  19984.22   4512.57   
7    1/1/2018 8:00  12422.88  1996.43   2883.96  1241.48  20289.37   4601.52   
8    1/1/2018 9:00  12605.15  2012.83   2880.94  1243.86  20338.61   4709.23   
9   1/1/2018 10:00  12852.52  2008.72   2888.71  1244.10  20250.29   4898.25   
10  1/1/2018 11:00  12915.23  1956.00   2862.09  1217.57  19996.93   5017.00   
11  1/1/2018 12:00  12898.77  1891.07   2833.66  1184.26  19485.20   5090.21   
12  1/1/2018 13:00  12799.62  1815.91   2783.86  1134.71  18761.46   5100.90   
13  1/1/2018 14:00  12561.39  1739.01   2726.05  1083.39  17929.19   5083.49   
14  1/1/2018 15:00  12276.08  1691.23   2677.41  1050.48  17300.43   5100.08   
15  1/1/2018 16:00  12013.03  1683.75   2641.89  1035.01  17035.04   5101.78   
16  1/1/2018 17:00  12163.41  1740.98   2641.47  1046.39  17279.86   5127.03   
17  1/1/2018 18:00  12904.77  1882.02   2704.64  1108.09  18599.94   5238.73   
18  1/1/2018 19:00  13557.38  1987.77   2857.67  1158.52  19778.25   5451.47   
19  1/1/2018 20:00  13638.32  2012.17   2893.80  1164.42  19960.20   5484.95   
20  1/1/2018 21:00  13662.92  2027.70   2900.22  1165.08  20001.50   5479.91   
21  1/1/2018 22:00  13500.73  2009.95   2881.12  1153.71  19719.39   5395.65   
22  1/1/2018 23:00  13104.63  1945.96   2831.64  1122.27  18993.50   5250.64   
23   1/2/2018 0:00  12677.63  1893.64   2773.98  1101.11  18346.96   5072.79   
24   1/2/2018 1:00  12954.54  1877.85   2908.41  1109.40  18245.55   5105.51   
25   1/2/2018 2:00  12762.33  1863.55   2896.25  1112.72  18041.58   5011.84   
26   1/2/2018 3:00  12672.32  1870.35   2903.21  1121.27  17954.64   4964.11   
27   1/2/2018 4:00  12720.79  1884.48   2914.42  1129.76  17999.01   4951.62   
28   1/2/2018 5:00  12982.67  1923.42   2931.03  1146.11  18313.72   4972.13   
29   1/2/2018 6:00  13540.02  2006.80   2974.96  1186.32  19110.14   5129.00   
30   1/2/2018 7:00  14259.42  2114.64   3034.23  1242.55  20146.48   5378.29   
31   1/2/2018 8:00  14662.85  2187.38   3072.45  1280.04  20703.41   5512.89   
32   1/2/2018 9:00  14847.38  2235.56   3040.62  1297.94  20821.65   5606.69   
33  1/2/2018 10:00  15078.54  2254.58   3034.99  1303.39  20987.82   5695.72   
34  1/2/2018 11:00  15249.14  2190.93   3030.59  1295.13  20975.02   5739.27   
35  1/2/2018 12:00  15162.50  2152.01   2996.40  1274.25  20799.50   5711.04   
36  1/2/2018 13:00  14982.16  2157.80   2946.62  1241.67  20494.03   5621.87   
37  1/2/2018 14:00  14868.70  2125.45   2921.38  1203.33  20298.20   5543.70   
38  1/2/2018 15:00  14784.34  2085.83   2897.57  1186.08  20172.90   5527.97   
39  1/2/2018 16:00  14708.81  2107.65   2835.93  1179.92  20255.11   5538.81   
40  1/2/2018 17:00  14844.78  2126.90   2809.17  1174.96  20683.04   5616.72   
41  1/2/2018 18:00  15397.70  2222.17   2859.86  1220.23  21580.65   5785.47   
42  1/2/2018 19:00  15655.35  2274.21   3003.97  1264.50  22168.94   6034.88   
43  1/2/2018 20:00  15562.07  2258.65   3044.37  1264.40  22015.78   6093.73   
44  1/2/2018 21:00  15390.07  2229.26   3054.22  1255.74  21687.86   6082.71   
45  1/2/2018 22:00  15016.04  2186.81   3025.22  1226.15  21024.75   5989.84   
46  1/2/2018 23:00  14447.10  2087.45   2976.39  1185.46  19962.69   5792.93   
47   1/3/2018 0:00  13951.71  2015.03   2931.94  1153.91  19261.95   5582.65   
48   1/3/2018 1:00  13364.63  1946.17   2802.05  1128.88  18582.42   5174.95   
49   1/3/2

Success. Dates are correct. 

*NOTE: The commented out code below denotes my process of deleting the daylight savings time hour. However, I've decided to keep the DST hour and the commented code can be disregared.*

In [288]:
#Drop the DST row 
#ercot2018_df = ercot2018_df.drop(7369)

In [289]:
#See if it dropped (7369 should be missing):
#ercot2018_df.loc[7359:7379]

Row has been dropped. Now reset df index so that we have 7369 again.

In [290]:
#Reset the index. "drop = True" so that another column isnt created
#ercot2018_df = ercot2018_df.reset_index(drop = True)

In [291]:
#Check to see that 7369 exists and no duplicate hours
#ercot2018_df.loc[7359:7379]

Let's check the number of rows to see if the row was successfully dropped. 

In [292]:
#Check the count of the rows
#ercot2018_df.count()

Success. It has one less row than before and now `7369` is included and it is not DST and there is no duplicate 2:00 hour.

---

#### Clean 2017 dates in `Hour_End`

Now to fix 2017 following the same steps as 2018:

In [293]:
#Repair 2017 df
#Separate the date and hours
ercot2017df_split = pd.DataFrame(ercot2017_df['Hour_End'].str.split(' ').tolist(), \
                                 columns = ['date', 'hour', 'DST'])

#Replace the five digit 'date' rows with nan
ercot2017df_split = ercot2017df_split.replace(to_replace = '\d{5}', value = np.nan, regex = True)

#Fill the NaN with '0:00'
ercot2017df_split['hour'] = ercot2017df_split['hour'].fillna('0:00')

#Now forward fill the 'hour'  column where NaN
ercot2017df_split['date'] = ercot2017df_split['date'].fillna(method = 'bfill')

#Fill in last hour of the dataset to be the next year
ercot2017df_split['date'].loc[8759] = '01/01/2018'

#Combine date and hour columns
ercot2017df_split['date'] = ercot2017df_split['date'] + ' ' + ercot2017df_split['hour'] 

#Find DST row
print(f'DST row for 2017: {ercot2017df_split.loc[ercot2017df_split["DST"] == "DST"]}')
print('\n')

#Drop DST row
ercot2017df_split = ercot2017df_split.drop(columns = ['hour', 'DST'])

#Make sure it has the same number of rows as the main 2017 df
print(f"Do the df have the same # of rows? {ercot2017_df['Hour_End'].count() == ercot2017df_split['date'].count()}")

#Replace old values with clean values
ercot2017_df['Hour_End'] = ercot2017df_split['date']

#Drop the DST row 
#ercot2017_df.drop(7393, inplace = True)

#Reset the index. "drop = True" so that another column isnt created
#ercot2017_df.reset_index(drop = True, inplace = True)

DST row for 2017:                   date   hour  DST
7393  11/05/2017 02:00  02:00  DST


Do the df have the same # of rows? True


---

Now repeat same process and clean 2019.

In [294]:
#Repair 2019 df
#Separate the date and hours
ercot2019df_split = pd.DataFrame(ercot2019_df['Hour_End'].str.split(' ').tolist(), \
                                 columns = ['date', 'hour', 'DST'])

#Replace the five digit 'date' rows with nan
ercot2019df_split = ercot2019df_split.replace(to_replace = '\d{5}', value = np.nan, regex = True)

#Fill the NaN with '0:00'
ercot2019df_split['hour'] = ercot2019df_split['hour'].fillna('0:00')

#Now forward fill the 'hour'  column where NaN
ercot2019df_split['date'] = ercot2019df_split['date'].fillna(method = 'bfill')

#Fill in last hour of the dataset to be the next year
ercot2019df_split['date'].loc[8759] = '01/01/2020'

#Combine date and hour columns
ercot2019df_split['date'] = ercot2019df_split['date'] + ' ' + ercot2019df_split['hour'] 

#Find DST row
DST_row = ercot2019df_split.loc[ercot2019df_split["DST"] == "DST"].index
print(f'DST row for 2019: {DST_row}')
print('\n')

#Drop DST row
ercot2019df_split = ercot2019df_split.drop(columns = ['hour', 'DST'])

#Make sure it has the same number of rows as the main 2019 df
print(f"Do the df have the same # of rows? {ercot2019_df['Hour_End'].count() == ercot2019df_split['date'].count()}")

#Replace old values with clean values
ercot2019_df['Hour_End'] = ercot2019df_split['date']

#Drop the DST row and last row (bc it's from 2020, which is not in this analysis)
#ercot2019_df.drop(DST_row, inplace = True) #Instead of hardcoding the row#, could replace with variable if I had more time. Move on

#Create variable for the 2020 row
drop_2020_row = ercot2019_df.loc[ercot2019_df['Hour_End'] == '01/01/2020 0:00'].index
ercot2019_df.drop(drop_2020_row, inplace = True) #Replace with date = 2020

#Reset the index. "drop = True" so that another column isnt created
#ercot2019_df.reset_index(drop = True, inplace = True)

DST row for 2019: Int64Index([7345], dtype='int64')


Do the df have the same # of rows? True


---

---

#### Address missing values in one row of 2016.

I noticed there is data missing for 1 day, and after going back to check the original CSV, it appears like it was missing from the beginning. I checked all other df, there are no missing values like this
#Lets fill in with the next week's data for the same hour

In [295]:
#Are there null values in 2016?
ercot2016_df.isnull().sum()

Hour_End    0
COAST       1
EAST        1
FAR_WEST    1
NORTH       1
NORTH_C     1
SOUTHERN    1
SOUTH_C     1
WEST        1
ERCOT       1
dtype: int64

In [296]:
#Where is the null row located?
ercot2016_df.loc[ercot2016_df['ERCOT'].isnull()]

Hour_End  COAST  EAST  FAR_WEST  NORTH  NORTH_C  SOUTHERN  \
7463  11/7/2016 0:00    NaN   NaN       NaN    NaN      NaN       NaN   

      SOUTH_C  WEST  ERCOT  
7463      NaN   NaN    NaN

The missing values row is at 7463. After seeing that the previous week was Halloween and might influence energy use late at night, and taking the average of the hours before misrepresents what was consistently seen at that hour in the weeks prior and after, I'll find and subsitute the following week's values. I will fill these in by hand since it's only one row in my whole 10 datasets and move one.

In [297]:
#What did the next week's value look like the midnight hour? (Also a Sunday night)
missing_values = ercot2016_df.loc[(7463+168)]
missing_values

Hour_End    11/14/2016 0:00
COAST             8437.5836
EAST              986.38804
FAR_WEST         1955.15221
NORTH             599.95893
NORTH_C           8685.1947
SOUTHERN          2385.7433
SOUTH_C          4497.31775
WEST              853.34844
ERCOT           28400.68697
Name: 7631, dtype: object

In [298]:
#Replace with following week's hour info
ercot2016_df.replace(to_replace = ercot2016_df.loc[7463][1:10], value = missing_values, inplace = True)

In [299]:
#Check for correction, that row 7463 has the same info as the hour a week ahead of time
ercot2016_df.loc[7463]

Hour_End    11/7/2016 0:00
COAST            8437.5836
EAST             986.38804
FAR_WEST        1955.15221
NORTH            599.95893
NORTH_C          8685.1947
SOUTHERN         2385.7433
SOUTH_C         4497.31775
WEST             853.34844
ERCOT          28400.68697
Name: 7463, dtype: object

In [300]:
#Any more nulls?
ercot2016_df.loc[ercot2016_df['ERCOT'].isnull()]

Empty DataFrame
Columns: [Hour_End, COAST, EAST, FAR_WEST, NORTH, NORTH_C, SOUTHERN, SOUTH_C, WEST, ERCOT]
Index: []

In [301]:
ercot2016_df.isnull().sum()

Hour_End    0
COAST       0
EAST        0
FAR_WEST    0
NORTH       0
NORTH_C     0
SOUTHERN    0
SOUTH_C     0
WEST        0
ERCOT       0
dtype: int64

Row has been updated appropriately. There are no longer any missing values for 2016.

---

### Final Dataset: 
Now we're done cleaning all the yearly datasets and can combine the 2008-2018 data for the final dataset.

In [302]:
#Concat 2008 - 2019 df
ercot_df = pd.concat([ercot2008_df, ercot2009_df, ercot2010_df, 
                      ercot2011_df, ercot2012_df, ercot2013_df, 
                      ercot2014_df, ercot2015_df, ercot2016_df, 
                      ercot2017_df, ercot2018_df, ercot2019_df])

ercot_df.reset_index(drop = True, inplace = True)

In [303]:
#Convert Hour_End to datetime
ercot_df['Hour_End'] = pd.to_datetime(ercot_df['Hour_End'])

#Check to see that Hour_End is in datetime format
ercot_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105191 entries, 0 to 105190
Data columns (total 10 columns):
 #   Column    Non-Null Count   Dtype         
---  ------    --------------   -----         
 0   Hour_End  105191 non-null  datetime64[ns]
 1   COAST     105191 non-null  float64       
 2   EAST      105191 non-null  float64       
 3   FAR_WEST  105191 non-null  float64       
 4   NORTH     105191 non-null  float64       
 5   NORTH_C   105191 non-null  float64       
 6   SOUTHERN  105191 non-null  float64       
 7   SOUTH_C   105191 non-null  float64       
 8   WEST      105191 non-null  float64       
 9   ERCOT     105191 non-null  float64       
dtypes: datetime64[ns](1), float64(9)
memory usage: 8.0 MB


Let's also make all the columns name lower case:

In [304]:
#Convert columns to lowercase
ercot_df.columns= ercot_df.columns.str.lower()
ercot_df

hour_end         coast         east     far_west  \
0      2008-01-01 01:00:00   7582.426275  1137.197278  1289.741591   
1      2008-01-01 02:00:00   7483.387277  1129.312429  1320.549720   
2      2008-01-01 03:00:00   7381.744778  1155.484647  1328.442079   
3      2008-01-01 04:00:00   7452.871868  1209.918355  1344.322369   
4      2008-01-01 05:00:00   7530.354017  1265.055389  1355.020035   
...                    ...           ...          ...          ...   
105186 2019-12-31 19:00:00  11326.000000  1416.720000  3624.610000   
105187 2019-12-31 20:00:00  11109.260000  1417.310000  3637.460000   
105188 2019-12-31 21:00:00  10846.500000  1411.760000  3639.020000   
105189 2019-12-31 22:00:00  10592.540000  1403.990000  3639.460000   
105190 2019-12-31 23:00:00  10304.620000  1387.050000  3630.180000   

              north      north_c     southern      south_c         west  \
0       1120.591245  10782.48780  1894.920943  4857.044340   932.251506   
1       1130.163920  10873.00119  1826.089194  4867.512567   939.958255   
2       1129.355056  10952.63748  1832.883827  4849.639885   951.322118   
3       1148.919804  11104.17876  1819.248340  4858.047321   967.450488   
4       1171.267839  11369.93504  1834.777369  4962.345559   996.055206   
...             ...          ...          ...          ...          ...   
105186   829.980000  13305.30000  3311.250000  6692.980000  1306.140000   
105187   825.760000  13164.66000  3181.360000  6453.700000  1290.260000   
105188   822.190000  12928.91000  3044.650000  6175.760000  1276.750000   
105189   819.390000  12716.27000  2930.560000  5968.290000  1260.090000   
105190   804.710000  12413.09000  2829.530000  5769.750000  1238.410000   

              ercot  
0       29596.66098  
1       29569.97455  
2       29581.50987  
3       29904.95730  
4       30484.81045  
...             ...  
105186  41812.98000  
105187  41079.76000  
105188  40145.54000  
105189  39330.60000  
105190  38377.36000  

[105191 rows x 10 columns]

And finally save all our hard work to a CSV:

In [305]:
#Save to csv
ercot_df.to_csv('ercot_2008_2019.csv', index = False)

I'll be using the dataset `ercot_2008_2019.csv` moving forward in EDA, modeling, and forecasting. 

### Voila!
---

# NOTE: 
Early in my process I thought I wanted to exclude leap days. I later decided against it and did not use the code below, but here is the code in the event that leap days want to be exlcuded:

### Drop leap days from 2008, 2012, 2016

#### Remove 2008's Leap Day

In [306]:
ercot2008_df.count()

Hour_End    8784
COAST       8784
EAST        8784
FAR_WEST    8784
NORTH       8784
NORTH_C     8784
SOUTHERN    8784
SOUTH_C     8784
WEST        8784
ERCOT       8784
dtype: int64

In [307]:
ercot2008_df.tail()

Hour_End        COAST         EAST     FAR_WEST        NORTH  \
8779  12/31/2008 20:00  8653.797723  1306.859687  1399.736364  1031.349295   
8780  12/31/2008 21:00  8335.906847  1288.140185  1404.396396  1031.299057   
8781  12/31/2008 22:00  8084.377432  1259.110206  1366.775572   999.853076   
8782  12/31/2008 23:00  7774.109816  1220.670565  1327.989067   981.698363   
8783     1/1/2009 0:00  7449.610400  1195.322050  1316.526000   956.971070   

          NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
8779  11460.45672  2251.695812  5605.751923  973.785467  32683.43299  
8780  11194.27760  2164.406221  5379.789851  964.508069  31762.72423  
8781  10932.66534  2056.149550  5162.265676  948.201988  30809.39884  
8782  10538.09417  1942.570201  4956.690254  930.771973  29672.59441  
8783  10425.22950  1826.227100  4761.973270  914.427160  28846.28655

In [308]:
#Find leap day row #'s for 2008
ercot2008_df.loc[ercot2008_df['Hour_End'] == '2/29/2008 0:00']

Hour_End      COAST        EAST    FAR_WEST      NORTH    NORTH_C  \
1415  2/29/2008 0:00  7536.6888  1122.01912  1059.97077  894.61096  8549.8812   

       SOUTHERN     SOUTH_C       WEST        ERCOT  
1415  1890.1312  4823.48732  724.00987  26600.79924

In [309]:
#Find all leap day rows
ercot2008_df.loc[1415:(1415+23)]

Hour_End        COAST         EAST     FAR_WEST        NORTH  \
1415   2/29/2008 0:00  7536.688800  1122.019120  1059.970770   894.610960   
1416   2/29/2008 1:00  7226.071449  1038.175643  1069.867530   866.904065   
1417   2/29/2008 2:00  7023.590623  1014.394020  1049.898473   820.446829   
1418   2/29/2008 3:00  6935.602097   967.057174  1049.743598   813.229690   
1419   2/29/2008 4:00  6971.670454   964.113906  1045.267329   811.064129   
1420   2/29/2008 5:00  7152.794332   998.141070  1065.826503   840.278421   
1421   2/29/2008 6:00  7711.628252  1085.005050  1126.809292   930.146003   
1422   2/29/2008 7:00  8597.667907  1257.816680  1210.828548  1087.952591   
1423   2/29/2008 8:00  8679.264329  1264.345357  1213.493926  1092.109563   
1424   2/29/2008 9:00  8821.623883  1226.213150  1173.345271  1060.977786   
1425  2/29/2008 10:00  9026.130393  1169.532912  1158.349348  1025.934095   
1426  2/29/2008 11:00  9360.503865  1194.174902  1138.168820  1022.932680   
1427  2/29/2008 12:00  9634.368883  1267.091234  1126.027805  1015.224560   
1428  2/29/2008 13:00  9653.801740  1270.510540  1113.221696  1000.563431   
1429  2/29/2008 14:00  9677.623266  1265.024024  1112.929342   993.784489   
1430  2/29/2008 15:00  9743.339613  1237.953323  1110.017603   976.255987   
1431  2/29/2008 16:00  9748.016334  1229.619458  1107.825577   971.524158   
1432  2/29/2008 17:00  9830.360928  1222.498342  1103.211220   971.605087   
1433  2/29/2008 18:00  9675.738964  1204.579885  1094.847198   962.759511   
1434  2/29/2008 19:00  9829.006923  1250.896212  1116.033814  1005.176973   
1435  2/29/2008 20:00  9866.262920  1270.890884  1159.946983  1046.212192   
1436  2/29/2008 21:00  9604.577391  1251.266740  1161.742269  1035.307228   
1437  2/29/2008 22:00  9238.611166  1173.098806  1139.641294  1007.978879   
1438  2/29/2008 23:00  8811.237351  1123.138524  1115.724095   954.761421   

           NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
1415   8549.881200  1890.131200  4823.487320  724.009870  26600.79924  
1416   7832.122960  1697.492692  4466.597701  698.745698  24895.97774  
1417   7609.685312  1616.981572  4318.593531  683.953608  24137.54397  
1418   7473.659749  1588.743287  4234.599411  689.481261  23752.11627  
1419   7473.664122  1570.556393  4230.437049  686.576912  23753.35030  
1420   7715.413147  1590.879458  4326.787222  702.313994  24392.43415  
1421   8463.064479  1698.589730  4705.752309  756.423800  26477.41892  
1422   9932.443043  1969.058676  5470.115745  863.647801  30389.53099  
1423  10547.484540  2053.875620  5660.028682  886.514697  31397.11671  
1424  10298.041450  2077.489302  5602.697428  863.715590  31124.10386  
1425  10286.841220  2172.577576  5670.564160  852.983873  31362.91358  
1426  10230.435210  2245.922375  5741.159482  838.484565  31771.78189  
1427  10068.737180  2306.452659  5774.274101  820.082973  32012.25940  
1428  10124.560220  2326.440033  5744.452212  810.446246  32043.99612  
1429  10175.832620  2373.471991  5721.365499  801.336539  32121.36777  
1430  10034.853460  2431.255669  5570.423073  792.419588  31896.51832  
1431   9970.477327  2468.816814  5593.799972  797.495528  31887.57517  
1432   9812.265601  2457.404082  5596.275373  794.670445  31788.29108  
1433   9751.749687  2414.571744  5547.265020  785.758173  31437.27018  
1434   9940.693032  2412.525831  5569.282811  811.901262  31935.51686  
1435  10129.856790  2530.488914  5708.031899  851.633757  32563.32434  
1436   9934.489756  2480.586255  5569.510937  827.205385  31864.68596  
1437   9602.142600  2357.604378  5326.836924  802.636355  30648.55040  
1438   9016.074345  2234.285414  4962.894698  763.567249  28981.68310

In [310]:
#Remove these rows and reset the index
#ercot2008_df.drop(range(1415,1439), axis = 0, inplace = True)

In [311]:
#Find all leap day rows
ercot2008_df.loc[1410:1440]

Hour_End        COAST         EAST     FAR_WEST        NORTH  \
1410  2/28/2008 19:00  9491.652416  1276.020250  1107.850842  1053.021554   
1411  2/28/2008 20:00  9747.297444  1375.618751  1161.431962  1105.404466   
1412  2/28/2008 21:00  9573.702409  1345.624272  1166.727498  1099.045785   
1413  2/28/2008 22:00  8855.051333  1314.638141  1142.154037  1061.327949   
1414  2/28/2008 23:00  8208.173884  1201.219407  1095.340667   969.471495   
1415   2/29/2008 0:00  7536.688800  1122.019120  1059.970770   894.610960   
1416   2/29/2008 1:00  7226.071449  1038.175643  1069.867530   866.904065   
1417   2/29/2008 2:00  7023.590623  1014.394020  1049.898473   820.446829   
1418   2/29/2008 3:00  6935.602097   967.057174  1049.743598   813.229690   
1419   2/29/2008 4:00  6971.670454   964.113906  1045.267329   811.064129   
1420   2/29/2008 5:00  7152.794332   998.141070  1065.826503   840.278421   
1421   2/29/2008 6:00  7711.628252  1085.005050  1126.809292   930.146003   
1422   2/29/2008 7:00  8597.667907  1257.816680  1210.828548  1087.952591   
1423   2/29/2008 8:00  8679.264329  1264.345357  1213.493926  1092.109563   
1424   2/29/2008 9:00  8821.623883  1226.213150  1173.345271  1060.977786   
1425  2/29/2008 10:00  9026.130393  1169.532912  1158.349348  1025.934095   
1426  2/29/2008 11:00  9360.503865  1194.174902  1138.168820  1022.932680   
1427  2/29/2008 12:00  9634.368883  1267.091234  1126.027805  1015.224560   
1428  2/29/2008 13:00  9653.801740  1270.510540  1113.221696  1000.563431   
1429  2/29/2008 14:00  9677.623266  1265.024024  1112.929342   993.784489   
1430  2/29/2008 15:00  9743.339613  1237.953323  1110.017603   976.255987   
1431  2/29/2008 16:00  9748.016334  1229.619458  1107.825577   971.524158   
1432  2/29/2008 17:00  9830.360928  1222.498342  1103.211220   971.605087   
1433  2/29/2008 18:00  9675.738964  1204.579885  1094.847198   962.759511   
1434  2/29/2008 19:00  9829.006923  1250.896212  1116.033814  1005.176973   
1435  2/29/2008 20:00  9866.262920  1270.890884  1159.946983  1046.212192   
1436  2/29/2008 21:00  9604.577391  1251.266740  1161.742269  1035.307228   
1437  2/29/2008 22:00  9238.611166  1173.098806  1139.641294  1007.978879   
1438  2/29/2008 23:00  8811.237351  1123.138524  1115.724095   954.761421   
1439    3/1/2008 0:00  8164.855700  1025.392400  1086.727740   887.415980   
1440    3/1/2008 1:00  7782.295147   942.664850  1071.603522   829.414536   

           NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
1410  10208.840030  2288.853979  5862.315014  827.244044  32115.79813  
1411  10668.917600  2427.985737  6165.169876  877.874729  33529.70057  
1412  10637.145600  2329.584918  6103.113674  862.971007  33117.91516  
1413  10350.316360  2246.503593  5835.386129  847.330271  31652.70781  
1414   9460.234910  2087.770119  5361.665310  784.670642  29168.54643  
1415   8549.881200  1890.131200  4823.487320  724.009870  26600.79924  
1416   7832.122960  1697.492692  4466.597701  698.745698  24895.97774  
1417   7609.685312  1616.981572  4318.593531  683.953608  24137.54397  
1418   7473.659749  1588.743287  4234.599411  689.481261  23752.11627  
1419   7473.664122  1570.556393  4230.437049  686.576912  23753.35030  
1420   7715.413147  1590.879458  4326.787222  702.313994  24392.43415  
1421   8463.064479  1698.589730  4705.752309  756.423800  26477.41892  
1422   9932.443043  1969.058676  5470.115745  863.647801  30389.53099  
1423  10547.484540  2053.875620  5660.028682  886.514697  31397.11671  
1424  10298.041450  2077.489302  5602.697428  863.715590  31124.10386  
1425  10286.841220  2172.577576  5670.564160  852.983873  31362.91358  
1426  10230.435210  2245.922375  5741.159482  838.484565  31771.78189  
1427  10068.737180  2306.452659  5774.274101  820.082973  32012.25940  
1428  10124.560220  2326.440033  5744.452212  810.446246  32043.99612  
1429  10175.832620  2373.471991  5721.365499  801.336539  32121.36777  
1430  10034.853460  2431.255669  557

Now reset the index.

In [312]:
#Reset the index. "drop = True" so that another column isnt created
#ercot2008_df.reset_index(drop = True, inplace = True)

In [313]:
#Find all leap day rows
ercot2008_df.loc[1410:(1410+10)]

Hour_End        COAST         EAST     FAR_WEST        NORTH  \
1410  2/28/2008 19:00  9491.652416  1276.020250  1107.850842  1053.021554   
1411  2/28/2008 20:00  9747.297444  1375.618751  1161.431962  1105.404466   
1412  2/28/2008 21:00  9573.702409  1345.624272  1166.727498  1099.045785   
1413  2/28/2008 22:00  8855.051333  1314.638141  1142.154037  1061.327949   
1414  2/28/2008 23:00  8208.173884  1201.219407  1095.340667   969.471495   
1415   2/29/2008 0:00  7536.688800  1122.019120  1059.970770   894.610960   
1416   2/29/2008 1:00  7226.071449  1038.175643  1069.867530   866.904065   
1417   2/29/2008 2:00  7023.590623  1014.394020  1049.898473   820.446829   
1418   2/29/2008 3:00  6935.602097   967.057174  1049.743598   813.229690   
1419   2/29/2008 4:00  6971.670454   964.113906  1045.267329   811.064129   
1420   2/29/2008 5:00  7152.794332   998.141070  1065.826503   840.278421   

           NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
1410  10208.840030  2288.853979  5862.315014  827.244044  32115.79813  
1411  10668.917600  2427.985737  6165.169876  877.874729  33529.70057  
1412  10637.145600  2329.584918  6103.113674  862.971007  33117.91516  
1413  10350.316360  2246.503593  5835.386129  847.330271  31652.70781  
1414   9460.234910  2087.770119  5361.665310  784.670642  29168.54643  
1415   8549.881200  1890.131200  4823.487320  724.009870  26600.79924  
1416   7832.122960  1697.492692  4466.597701  698.745698  24895.97774  
1417   7609.685312  1616.981572  4318.593531  683.953608  24137.54397  
1418   7473.659749  1588.743287  4234.599411  689.481261  23752.11627  
1419   7473.664122  1570.556393  4230.437049  686.576912  23753.35030  
1420   7715.413147  1590.879458  4326.787222  702.313994  24392.43415

In [314]:
ercot2008_df.count()

Hour_End    8784
COAST       8784
EAST        8784
FAR_WEST    8784
NORTH       8784
NORTH_C     8784
SOUTHERN    8784
SOUTH_C     8784
WEST        8784
ERCOT       8784
dtype: int64

In [315]:
ercot2008_df.tail()

Hour_End        COAST         EAST     FAR_WEST        NORTH  \
8779  12/31/2008 20:00  8653.797723  1306.859687  1399.736364  1031.349295   
8780  12/31/2008 21:00  8335.906847  1288.140185  1404.396396  1031.299057   
8781  12/31/2008 22:00  8084.377432  1259.110206  1366.775572   999.853076   
8782  12/31/2008 23:00  7774.109816  1220.670565  1327.989067   981.698363   
8783     1/1/2009 0:00  7449.610400  1195.322050  1316.526000   956.971070   

          NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
8779  11460.45672  2251.695812  5605.751923  973.785467  32683.43299  
8780  11194.27760  2164.406221  5379.789851  964.508069  31762.72423  
8781  10932.66534  2056.149550  5162.265676  948.201988  30809.39884  
8782  10538.09417  1942.570201  4956.690254  930.771973  29672.59441  
8783  10425.22950  1826.227100  4761.973270  914.427160  28846.28655

2008 Leap Day has been removed.

---

#### Remove 2012's leap day:

In [316]:
ercot2012_df.count()

Hour_End    8784
COAST       8784
EAST        8784
FAR_WEST    8784
NORTH       8784
NORTH_C     8784
SOUTHERN    8784
SOUTH_C     8784
WEST        8784
ERCOT       8784
dtype: int64

In [317]:
ercot2012_df.tail()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
8779  12/31/2012 20:00  9231.033570  1306.377467  1493.665212  861.065108   
8780  12/31/2012 21:00  8865.645755  1258.102074  1486.707317  841.805345   
8781  12/31/2012 22:00  8527.194858  1140.036890  1475.875350  821.077843   
8782  12/31/2012 23:00  8185.989966  1121.583439  1456.711482  798.205052   
8783     1/1/2013 0:00  7893.398200  1088.466640  1439.204660  778.922080   

          NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
8779  12829.06199  2885.694244  5676.152908  1012.237955  35295.28845  
8780  12260.95647  2751.366935  5374.905326   987.701591  33827.19081  
8781  11718.37788  2609.661205  5103.819112   966.436026  32362.47917  
8782  11150.10965  2459.220415  4841.914447   937.489827  30951.22428  
8783  10730.75780  2315.334400  4591.715770   909.939940  29747.73949

In [318]:
#Find leap day row #'s for 2012
ercot2012_df.loc[ercot2012_df['Hour_End'] == '2/29/2012 0:00']

Hour_End      COAST        EAST    FAR_WEST      NORTH   NORTH_C  \
1415  2/29/2012 0:00  7985.4844  1045.09205  1234.94415  647.02778  8938.517   

       SOUTHERN     SOUTH_C       WEST        ERCOT  
1415  2418.4445  4570.73293  793.50711  27633.74992

In [319]:
#Find all leap day rows
ercot2012_df.loc[1415:(1415+23)]

Hour_End         COAST         EAST     FAR_WEST       NORTH  \
1415   2/29/2012 0:00   7985.484400  1045.092050  1234.944150  647.027780   
1416   2/29/2012 1:00   7504.034833  1011.259712  1150.723663  602.856111   
1417   2/29/2012 2:00   7211.485054   976.506971  1155.646172  581.620686   
1418   2/29/2012 3:00   7036.966873   948.352013  1156.803598  576.562855   
1419   2/29/2012 4:00   6983.999843   935.679265  1168.812026  576.329423   
1420   2/29/2012 5:00   7123.790115   952.987955  1198.030656  590.408985   
1421   2/29/2012 6:00   7687.310309   988.235548  1261.464634  632.590493   
1422   2/29/2012 7:00   8648.207277  1090.793228  1358.315953  724.373133   
1423   2/29/2012 8:00   8788.358779  1117.577407  1394.756085  751.031646   
1424   2/29/2012 9:00   8972.565487  1137.693279  1383.361655  735.944709   
1425  2/29/2012 10:00   9348.574750  1165.455509  1370.092204  732.262640   
1426  2/29/2012 11:00   9725.264941  1194.190598  1358.299907  728.333427   
1427  2/29/2012 12:00  10078.614880  1198.084403  1354.777760  723.583660   
1428  2/29/2012 13:00  10331.420130  1192.780085  1339.059848  716.184295   
1429  2/29/2012 14:00  10529.538080  1187.099647  1340.346158  723.385659   
1430  2/29/2012 15:00  10692.229940  1189.011761  1335.339228  717.989032   
1431  2/29/2012 16:00  10800.973070  1193.283531  1328.297740  714.453980   
1432  2/29/2012 17:00  10723.507950  1207.205493  1344.949429  713.405915   
1433  2/29/2012 18:00  10493.793300  1205.090190  1343.415682  704.397417   
1434  2/29/2012 19:00  10605.876040  1258.144541  1347.869896  741.003645   
1435  2/29/2012 20:00  10699.066750  1278.282692  1387.754839  758.883005   
1436  2/29/2012 21:00  10494.771400  1242.044713  1380.819828  747.718425   
1437  2/29/2012 22:00  10013.063030  1179.514155  1354.729468  734.605535   
1438  2/29/2012 23:00   9266.580370  1075.363405  1297.078776  683.839083   

           NORTH_C     SOUTHERN      SOUTH_C        WEST        ERCOT  
1415   8938.517000  2418.444500  4570.732930  793.507110  27633.74992  
1416   8272.558742  2237.527368  4193.708204  744.010294  25716.67893  
1417   7876.124540  2116.657682  3970.104767  719.198532  24607.34440  
1418   7662.614044  2056.502142  3813.649368  707.170354  23958.62125  
1419   7595.018245  2028.095924  3794.369945  705.864023  23788.16869  
1420   7780.344173  2032.883249  3842.544520  716.998260  24237.98791  
1421   8464.280930  2169.541289  4201.731731  766.068701  26171.22364  
1422   9879.348505  2479.177407  4908.562911  866.366010  29955.14442  
1423  10386.968540  2573.649914  5168.087208  901.487868  31081.91744  
1424  10270.065520  2591.385721  5153.669882  897.473045  31142.15930  
1425  10391.690900  2675.582854  5274.246718  900.643150  31858.54872  
1426  10592.795970  2793.415778  5372.692698  904.072627  32669.06595  
1427  10655.732750  2904.077195  5329.094917  901.490061  33145.45562  
1428  10675.341920  2992.236894  5350.040874  898.247557  33495.31160  
1429  10842.077240  3112.549647  5443.653946  894.819125  34073.46951  
1430  10880.726020  3216.941928  5542.727861  897.656728  34472.62250  
1431  10870.304210  3271.508250  5642.102350  903.294111  34724.21724  
1432  10897.884590  3300.035955  5630.708597  904.962629  34722.66055  
1433  10838.933220  3223.343149  5535.400591  900.460402  34244.83396  
1434  11143.929480  3185.591445  5687.217193  917.126880  34886.75913  
1435  11303.336230  3277.117897  5896.426670  956.371177  35557.23926  
1436  11079.672540  3181.088334  5757.408444  940.891253  34824.41493  
1437  10652.642880  2998.785956  5420.146476  910.404247  33263.89175  
1438   9726.496049  2760.639883  4957.365646  846.850148  30614.21336

In [320]:
#Remove these rows and reset the index
#ercot2012_df.drop(range(1415,1439), axis = 0, inplace = True)

#Reset the index. "drop = True" so that another column isnt created
#ercot2012_df.reset_index(drop = True, inplace = True)

#Find all leap day rows
ercot2012_df.loc[1410:(1410+10)]

print(ercot2012_df.count())

Hour_End    8784
COAST       8784
EAST        8784
FAR_WEST    8784
NORTH       8784
NORTH_C     8784
SOUTHERN    8784
SOUTH_C     8784
WEST        8784
ERCOT       8784
dtype: int64


In [321]:
ercot2012_df.tail()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
8779  12/31/2012 20:00  9231.033570  1306.377467  1493.665212  861.065108   
8780  12/31/2012 21:00  8865.645755  1258.102074  1486.707317  841.805345   
8781  12/31/2012 22:00  8527.194858  1140.036890  1475.875350  821.077843   
8782  12/31/2012 23:00  8185.989966  1121.583439  1456.711482  798.205052   
8783     1/1/2013 0:00  7893.398200  1088.466640  1439.204660  778.922080   

          NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
8779  12829.06199  2885.694244  5676.152908  1012.237955  35295.28845  
8780  12260.95647  2751.366935  5374.905326   987.701591  33827.19081  
8781  11718.37788  2609.661205  5103.819112   966.436026  32362.47917  
8782  11150.10965  2459.220415  4841.914447   937.489827  30951.22428  
8783  10730.75780  2315.334400  4591.715770   909.939940  29747.73949

2012 Leap Day has been removed.

---

#### Remove 2016's leap day:

In [322]:
ercot2016_df.count()

Hour_End    8784
COAST       8784
EAST        8784
FAR_WEST    8784
NORTH       8784
NORTH_C     8784
SOUTHERN    8784
SOUTH_C     8784
WEST        8784
ERCOT       8784
dtype: int64

In [323]:
ercot2016_df.tail()

Hour_End         COAST         EAST     FAR_WEST       NORTH  \
8779  12/31/2016 20:00  10235.077690  1194.606574  2089.906797  730.796890   
8780  12/31/2016 21:00   9985.988411  1161.754671  2063.540266  718.952325   
8781  12/31/2016 22:00   9668.239226  1106.560529  2045.303156  713.668403   
8782  12/31/2016 23:00   9332.315239  1076.492598  2018.220017  704.164722   
8783     1/1/2017 0:00   9029.597200  1029.875730  1991.563500  689.630460   

           NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
8779  10948.101490  2972.484950  5712.730175  1014.881335  34898.58590  
8780  10577.314420  2803.337250  5423.515665   994.305521  33728.70853  
8781  10200.589060  2655.172757  5172.592743   975.840716  32537.96659  
8782   9846.657014  2534.890339  4930.975674   950.065468  31393.78107  
8783   9543.490800  2427.623800  4707.750510   932.266730  30351.79873

In [324]:
#Find leap day row #'s for 2016
ercot2016_df.loc[ercot2016_df['Hour_End'] == '2/29/2016 0:00']

Hour_End      COAST        EAST    FAR_WEST      NORTH    NORTH_C  \
1415  2/29/2016 0:00  8411.2651  1022.71582  1836.15437  616.04217  8641.8175   

       SOUTHERN     SOUTH_C       WEST        ERCOT  
1415  2416.1532  4555.08914  843.36763  28342.60493

In [325]:
#Find all leap day rows
ercot2016_df.loc[1415:(1415+23)]

Hour_End         COAST         EAST     FAR_WEST       NORTH  \
1415   2/29/2016 0:00   8411.265100  1022.715820  1836.154370  616.042170   
1416   2/29/2016 1:00   7976.593430   960.344204  1807.674170  591.014828   
1417   2/29/2016 2:00   7746.868689   902.111622  1801.888985  584.456374   
1418   2/29/2016 3:00   7661.940643   929.456225  1804.923777  569.200456   
1419   2/29/2016 4:00   7664.649527   914.477487  1812.324147  576.687310   
1420   2/29/2016 5:00   7898.223509   935.825397  1832.971540  600.001784   
1421   2/29/2016 6:00   8511.724854  1031.866023  1878.310510  644.207986   
1422   2/29/2016 7:00   9353.967585  1179.196740  1974.978646  728.142025   
1423   2/29/2016 8:00   9531.675481  1200.226411  2014.179059  759.113439   
1424   2/29/2016 9:00   9738.667498  1185.103634  1985.935142  745.662532   
1425  2/29/2016 10:00  10011.738550  1245.140232  1975.548628  735.004552   
1426  2/29/2016 11:00  10289.642130  1251.800018  1980.975102  727.404445   
1427  2/29/2016 12:00  10540.494990  1262.905301  1984.923109  719.808016   
1428  2/29/2016 13:00  10711.691740  1258.943708  1991.826508  713.492023   
1429  2/29/2016 14:00  10952.489950  1268.317393  2013.176657  717.347542   
1430  2/29/2016 15:00  11058.550750  1277.214793  2026.377741  714.845654   
1431  2/29/2016 16:00  11087.108020  1278.945599  2028.833390  712.335524   
1432  2/29/2016 17:00  11037.916380  1278.620291  2020.758622  711.872555   
1433  2/29/2016 18:00  10893.278330  1265.955889  2008.445261  709.426838   
1434  2/29/2016 19:00  10963.307750  1326.760638  1998.590913  733.811972   
1435  2/29/2016 20:00  11074.097240  1349.574425  2035.216847  755.936219   
1436  2/29/2016 21:00  10777.076670  1309.806856  2021.616242  740.143611   
1437  2/29/2016 22:00  10270.228950  1259.407576  1987.247731  706.034643   
1438  2/29/2016 23:00   9530.344106  1150.708330  1921.758633  657.398488   

           NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
1415   8641.817500  2416.153200  4555.089140   843.367630  28342.60493  
1416   8043.809856  2200.993552  4205.904121   857.281022  26643.61518  
1417   7753.870041  2072.984055  3988.415219   845.916850  25696.51184  
1418   7646.347519  2014.638266  3888.890530   840.449662  25355.84708  
1419   7721.620088  1989.416866  3872.247211   847.523916  25398.94655  
1420   8083.586787  2018.146174  3969.129261   871.154253  26209.03870  
1421   9007.949169  2163.647511  4390.967359   929.512067  28558.18548  
1422  10552.530120  2493.511229  5086.775526  1041.421796  32410.52367  
1423  11057.704140  2584.848025  5321.738707  1086.364169  33555.84943  
1424  10909.211190  2594.035504  5328.890153  1066.182327  33553.68798  
1425  10903.381280  2679.329764  5409.908605  1050.193084  34010.24469  
1426  10962.199760  2778.384863  5502.938894  1041.741485  34535.08670  
1427  10969.202950  2887.174971  5575.020159  1035.750012  34975.27950  
1428  11010.141890  2988.385952  5640.920815  1035.618016  35351.02065  
1429  11091.415630  3101.920924  5724.938846  1042.664433  35912.27138  
1430  11169.165550  3212.569749  5802.496223  1048.365662  36309.58613  
1431  11172.281370  3287.479046  5878.817581  1053.476654  36499.27719  
1432  11171.372020  3307.537263  5961.161191  1063.769336  36553.00765  
1433  11214.573610  3220.396255  6016.407232  1057.145829  36385.62924  
1434  11599.119050  3189.827101  6193.805380  1077.645243  37082.86805  
1435  11933.135630  3301.146710  6393.685074  1108.010752  37950.80289  
1436  11665.635480  3232.362471  6226.671668  1083.479072  37056.79207  
1437  11101.960530  3094.073762  5835.640016  1043.803619  35298.39682  
1438  10136.013100  2856.012960  5281.232835   977.788181  32511.25664

In [326]:
#Remove these rows and reset the index
#ercot2016_df.drop(range(1415,1439), axis = 0, inplace = True)

#Reset the index. "drop = True" so that another column isnt created
#ercot2016_df.reset_index(drop = True, inplace = True)

#Find all leap day rows
ercot2016_df.loc[1410:(1410+10)]

print(ercot2016_df.count())

Hour_End    8784
COAST       8784
EAST        8784
FAR_WEST    8784
NORTH       8784
NORTH_C     8784
SOUTHERN    8784
SOUTH_C     8784
WEST        8784
ERCOT       8784
dtype: int64


There are missing values, need to address. 

In [327]:
ercot2016_df.tail()

Hour_End         COAST         EAST     FAR_WEST       NORTH  \
8779  12/31/2016 20:00  10235.077690  1194.606574  2089.906797  730.796890   
8780  12/31/2016 21:00   9985.988411  1161.754671  2063.540266  718.952325   
8781  12/31/2016 22:00   9668.239226  1106.560529  2045.303156  713.668403   
8782  12/31/2016 23:00   9332.315239  1076.492598  2018.220017  704.164722   
8783     1/1/2017 0:00   9029.597200  1029.875730  1991.563500  689.630460   

           NORTH_C     SOUTHERN      SOUTH_C         WEST        ERCOT  
8779  10948.101490  2972.484950  5712.730175  1014.881335  34898.58590  
8780  10577.314420  2803.337250  5423.515665   994.305521  33728.70853  
8781  10200.589060  2655.172757  5172.592743   975.840716  32537.96659  
8782   9846.657014  2534.890339  4930.975674   950.065468  31393.78107  
8783   9543.490800  2427.623800  4707.750510   932.266730  30351.79873

2016 Leap Day has been removed.